# 接続先設定 (ポートはdockerで成功したほうに合わせてください)
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1
spring.datasource.username=system
spring.datasource.password=pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernateの設定 (テーブルを自動で作ってくれる設定)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect